#!/bin/sh

. /etc/container_environment.sh
. /etc/superpaper/env.sh

cd /superpaper/services/document-updater && /sbin/setuser www-data node scripts/flush_all.js >> /var/log/superpaper/document-updater.log 2>&1

EXIT_CODE="$?"
if [ $EXIT_CODE -ne 0 ]
then
  echo "document-updater/scripts/flush_all.js failed with exit code $EXIT_CODE"
  exit 1
fi

exit 0
