export CHAT_HOST=127.0.0.1
export CLSI_HOST=127.0.0.1
export CONTACTS_HOST=127.0.0.1
export DOCSTORE_HOST=127.0.0.1
export DOCUMENT_UPDATER_HOST=127.0.0.1
export DOCUPDATER_HOST=127.0.0.1
export FILESTORE_HOST=127.0.0.1
export HISTORY_V1_HOST=127.0.0.1
export NOTIFICATIONS_HOST=127.0.0.1
export PROJECT_HISTORY_HOST=127.0.0.1
export REALTIME_HOST=127.0.0.1
export WEB_HOST=127.0.0.1
export WEB_API_HOST=127.0.0.1

if [ -z "${SUPERPAPER_MONGO_URL:-}" ] && [ -n "${OVERLEAF_MONGO_URL:-}" ]; then
  export SUPERPAPER_MONGO_URL="$OVERLEAF_MONGO_URL"
fi

if [ -z "${SUPERPAPER_REDIS_HOST:-}" ]; then
  export SUPERPAPER_REDIS_HOST="${OVERLEAF_REDIS_HOST:-${REDIS_HOST:-}}"
fi

if [ -z "${SUPERPAPER_REDIS_PORT:-}" ]; then
  export SUPERPAPER_REDIS_PORT="${OVERLEAF_REDIS_PORT:-${REDIS_PORT:-6379}}"
fi

if [ -z "${SUPERPAPER_REDIS_PASS:-}" ] && [ -n "${OVERLEAF_REDIS_PASS:-}" ]; then
  export SUPERPAPER_REDIS_PASS="$OVERLEAF_REDIS_PASS"
fi

if [ -z "${SUPERPAPER_REDIS_TLS:-}" ] && [ -n "${OVERLEAF_REDIS_TLS:-}" ]; then
  export SUPERPAPER_REDIS_TLS="$OVERLEAF_REDIS_TLS"
fi

if [ -z "${SUPERPAPER_STORAGE_ROOT:-}" ] && [ -n "${OVERLEAF_STORAGE_ROOT:-}" ]; then
  export SUPERPAPER_STORAGE_ROOT="$OVERLEAF_STORAGE_ROOT"
fi

if [ -z "${SUPERPAPER_STORAGE_ROOT:-}" ]; then
  if findmnt -n /var/lib/superpaper >/dev/null 2>&1; then
    export SUPERPAPER_STORAGE_ROOT=/var/lib/superpaper
  elif findmnt -n /var/lib/overleaf >/dev/null 2>&1 || [ -d /var/lib/overleaf ]; then
    export SUPERPAPER_STORAGE_ROOT=/var/lib/overleaf
  else
    export SUPERPAPER_STORAGE_ROOT=/var/lib/superpaper
  fi
fi

SUPERPAPER_HISTORY_PREFIX=superpaper
if [ "$SUPERPAPER_STORAGE_ROOT" = "/var/lib/overleaf" ]; then
  SUPERPAPER_HISTORY_PREFIX=overleaf
fi

export SUPERPAPER_HISTORY_BACKEND="${SUPERPAPER_HISTORY_BACKEND:-fs}"
export SUPERPAPER_HISTORY_PROJECT_BLOBS_BUCKET="${SUPERPAPER_HISTORY_PROJECT_BLOBS_BUCKET:-${OVERLEAF_HISTORY_PROJECT_BLOBS_BUCKET:-$SUPERPAPER_STORAGE_ROOT/data/history/$SUPERPAPER_HISTORY_PREFIX-project-blobs}}"
export SUPERPAPER_HISTORY_BLOBS_BUCKET="${SUPERPAPER_HISTORY_BLOBS_BUCKET:-${OVERLEAF_HISTORY_BLOBS_BUCKET:-$SUPERPAPER_STORAGE_ROOT/data/history/$SUPERPAPER_HISTORY_PREFIX-global-blobs}}"
export SUPERPAPER_HISTORY_CHUNKS_BUCKET="${SUPERPAPER_HISTORY_CHUNKS_BUCKET:-${OVERLEAF_HISTORY_CHUNKS_BUCKET:-$SUPERPAPER_STORAGE_ROOT/data/history/$SUPERPAPER_HISTORY_PREFIX-chunks}}"
export SUPERPAPER_HISTORY_ZIPS_BUCKET="${SUPERPAPER_HISTORY_ZIPS_BUCKET:-${OVERLEAF_HISTORY_ZIPS_BUCKET:-$SUPERPAPER_STORAGE_ROOT/data/history/$SUPERPAPER_HISTORY_PREFIX-zips}}"
