#!/bin/bash

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - docstore"
    NODE_PARAMS="--inspect=0.0.0.0:30160"
fi

source /etc/superpaper/env.sh
export LISTEN_ADDRESS=127.0.0.1

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /superpaper/services/docstore/app.js >> /var/log/superpaper/docstore.log 2>&1
