export type AdminCapability =
  | 'clear-session'
  | 'delete-2fa'
  | 'delete-project'
  | 'modify-admin'
  | 'modify-feature-override'
  | 'modify-group'
  | 'modify-group-manager'
  | 'modify-group-member'
  | 'modify-group-setting'
  | 'modify-managed-group'
  | 'modify-managed-group-member'
  | 'modify-project-content'
  | 'modify-project-setting'
  | 'modify-user-account-status'
  | 'modify-user-email'
  | 'modify-user-name'
  | 'view-audit-log'
  | 'view-group-manager'
  | 'view-project-content'
  | 'view-project-setting'
  | 'view-script-log'
  | 'view-session'
  | 'view-user-additional-info'

export type AdminRole =
  | 'engagement'
  | 'engineering'
  | 'finance'
  | 'product'
  | 'sales'
  | 'sales_support'
  | 'super_admin'
  | 'support'
  | 'support_tier_1'
  | 'ux'
